# This is a basic workflow to help you get started with Actions

name: convert-txt-to-pdf

on:
  push:
    branches: [ "main" ]
    paths:
      - 'inbound/**/*.txt'
      - 'inbound/*.txt'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install reportlab

      - name: Convert inbound .txt files to PDFs and commit to outbound/
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@users.noreply.github.com
        run: |
          set -e
          python convert_txt_to_pdf.py

          # stage and commit any changes in outbound/
          git add outbound || true
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "${GIT_AUTHOR_NAME}"
            git config user.email "${GIT_AUTHOR_EMAIL}"
            git commit -m "Convert inbound txt to pdf [skip ci]" || true
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
